name: Update Database

on:
  schedule:
    # Run twice per day (at 1:00UTC/6pmPST, 13:00UTC/6amPST)
    - cron:  '0 1,13 * * *'
  workflow_dispatch:

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
          # token: ${{ secrets.COMMIT_TOKEN }}
          # ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --frozen-lockfile # optional, --immutable

      - run: yarn generate

      - uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          # token: ${{ secrets.COMMIT_TOKEN }}
          commit-message: 'feat: periodic database update'
          committer: 'GitHub <noreply@github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: feature/periodic-update
          branch-suffix: timestamp
          delete-branch: true
          title: 'feat: periodic database update'
          body: |
            Update known addresses database
            
            Co-authored-by: peter-evans <leon0399@users.noreply.github.com>
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
    permissions:
      contents: write
      pull-requests: write
