name: Update Database

on:
  schedule:
    # Run twice per day (at 1:00UTC/6pmPST, 13:00UTC/6amPST)
    - cron:  '0 1,13 * * *'
  workflow_dispatch:

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
          # token: ${{ secrets.COMMIT_TOKEN }}
          # ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --frozen-lockfile # optional, --immutable

      - run: yarn generate

      - uses: peter-evans/create-pull-request@v4
        with:
          # token: ${{ secrets.COMMIT_TOKEN }}
          commit-message: 'feat: periodic database update'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          branch-suffix: timestamp
          delete-branch: true
          title: 'feat: periodic database update'
          body: |
            Update known addresses database

            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
